services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python main.py"

  test:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: db
    command: ["pytest", "app/tests/"]
    volumes:
      - .:/app

volumes:
  postgres_data: